/*
  File autogenerated by gengetopt version 2.22.6
  generated with the following command:
  gengetopt --input=icee_cmdline.ggo --no-handle-version --func-name=icee_cmdline_parser --file=icee_cmdline --arg-struct-name=icee_args_info

  The developers of gengetopt consider the fixed text that goes in all
  gengetopt output files to be in the public domain:
  we make no copyright claims on it.
*/

/* If we use autoconf.  */
#ifdef HAVE_CONFIG_H
#include "config.h"
#endif

#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#ifndef FIX_UNUSED
#define FIX_UNUSED(X) (void) (X) /* avoid warnings for unused params */
#endif

#include <getopt.h>

#include "icee_cmdline.h"

const char *icee_args_info_purpose = "";

const char *icee_args_info_usage = "Usage: icee [OPTIONS]...";

const char *icee_args_info_versiontext = "";

const char *icee_args_info_description = "";

const char *icee_args_info_help[] = {
  "  -h, --help                Print help and exit",
  "  -V, --version             Print version and exit",
  "  -c, --client              Client mode  (default=off)",
  "  -w, --writemethod=STRING  ADIOS write method  (default=`POSIX1')",
  "  -r, --readmethod=STRING   ADIOS read method  (default=`BP')",
  "  -n, --len=LONGLONG        array length  (default=`1')",
  "      --chunk=LONGLONG      chunk length  (default=`131072')",
  "      --timeout=FLOAT       Timeout  (default=`10.0')",
  "      --sleep=INT           interval time  (default=`5')",
  "      --nstep=INT           number of time steps  (default=`10')",
  "      --wparam=STRING       write method params  (default=`')",
  "      --rparam=STRING       read method params  (default=`')",
  "      --prefix=STRING       prefix  (default=`')",
  "      --append              append  (default=off)",
  "      --filename=STRING     filename",
  "      --mpicolor=INT        MPI comm color  (default=`0')",
  "      --filelock=STRING     filelock name",
  "      --evilread            enable evil read  (default=off)",
  "      --commself            commself  (default=off)",
  "      --host=STRING         local hostname  (default=`localhost')",
  "  -p, --port=INT            local port  (default=`59900')",
  "  -s, --remotehost=STRING   remote hostname  (default=`localhost')",
  "  -t, --remoteport=INT      remote port  (default=`59900')",
  "  -T, --method=STRING       EVPath method  (default=`TCP')",
  "  -v, --verbose=INT         verbosity level  (default=`3')",
  "  -e, --contact=STRING      EVPath contact string",
  "      --passive             enable passive mode  (default=off)",
  "      --nclient=INT         maximum number of clients",
  "      --isnative            use native contact  (default=off)",
  "      --remotelist=STRING   remote list",
  "  -a, --attrlist=STRING     attr list",
    0
};

typedef enum {ARG_NO
  , ARG_FLAG
  , ARG_STRING
  , ARG_INT
  , ARG_FLOAT
  , ARG_LONGLONG
} icee_cmdline_parser_arg_type;

static
void clear_given (struct icee_args_info *args_info);
static
void clear_args (struct icee_args_info *args_info);

static int
icee_cmdline_parser_internal (int argc, char **argv, struct icee_args_info *args_info,
                        struct icee_cmdline_parser_params *params, const char *additional_error);

static int
icee_cmdline_parser_required2 (struct icee_args_info *args_info, const char *prog_name, const char *additional_error);

static char *
gengetopt_strdup (const char *s);

static
void clear_given (struct icee_args_info *args_info)
{
  args_info->help_given = 0 ;
  args_info->version_given = 0 ;
  args_info->client_given = 0 ;
  args_info->writemethod_given = 0 ;
  args_info->readmethod_given = 0 ;
  args_info->len_given = 0 ;
  args_info->chunk_given = 0 ;
  args_info->timeout_given = 0 ;
  args_info->sleep_given = 0 ;
  args_info->nstep_given = 0 ;
  args_info->wparam_given = 0 ;
  args_info->rparam_given = 0 ;
  args_info->prefix_given = 0 ;
  args_info->append_given = 0 ;
  args_info->filename_given = 0 ;
  args_info->mpicolor_given = 0 ;
  args_info->filelock_given = 0 ;
  args_info->evilread_given = 0 ;
  args_info->commself_given = 0 ;
  args_info->host_given = 0 ;
  args_info->port_given = 0 ;
  args_info->remotehost_given = 0 ;
  args_info->remoteport_given = 0 ;
  args_info->method_given = 0 ;
  args_info->verbose_given = 0 ;
  args_info->contact_given = 0 ;
  args_info->passive_given = 0 ;
  args_info->nclient_given = 0 ;
  args_info->isnative_given = 0 ;
  args_info->remotelist_given = 0 ;
  args_info->attrlist_given = 0 ;
}

static
void clear_args (struct icee_args_info *args_info)
{
  FIX_UNUSED (args_info);
  args_info->client_flag = 0;
  args_info->writemethod_arg = gengetopt_strdup ("POSIX1");
  args_info->writemethod_orig = NULL;
  args_info->readmethod_arg = gengetopt_strdup ("BP");
  args_info->readmethod_orig = NULL;
  args_info->len_arg = 1;
  args_info->len_orig = NULL;
  args_info->chunk_arg = 131072;
  args_info->chunk_orig = NULL;
  args_info->timeout_arg = 10.0;
  args_info->timeout_orig = NULL;
  args_info->sleep_arg = 5;
  args_info->sleep_orig = NULL;
  args_info->nstep_arg = 10;
  args_info->nstep_orig = NULL;
  args_info->wparam_arg = gengetopt_strdup ("");
  args_info->wparam_orig = NULL;
  args_info->rparam_arg = gengetopt_strdup ("");
  args_info->rparam_orig = NULL;
  args_info->prefix_arg = gengetopt_strdup ("");
  args_info->prefix_orig = NULL;
  args_info->append_flag = 0;
  args_info->filename_arg = NULL;
  args_info->filename_orig = NULL;
  args_info->mpicolor_arg = 0;
  args_info->mpicolor_orig = NULL;
  args_info->filelock_arg = NULL;
  args_info->filelock_orig = NULL;
  args_info->evilread_flag = 0;
  args_info->commself_flag = 0;
  args_info->host_arg = gengetopt_strdup ("localhost");
  args_info->host_orig = NULL;
  args_info->port_arg = 59900;
  args_info->port_orig = NULL;
  args_info->remotehost_arg = gengetopt_strdup ("localhost");
  args_info->remotehost_orig = NULL;
  args_info->remoteport_arg = 59900;
  args_info->remoteport_orig = NULL;
  args_info->method_arg = gengetopt_strdup ("TCP");
  args_info->method_orig = NULL;
  args_info->verbose_arg = 3;
  args_info->verbose_orig = NULL;
  args_info->contact_arg = NULL;
  args_info->contact_orig = NULL;
  args_info->passive_flag = 0;
  args_info->nclient_orig = NULL;
  args_info->isnative_flag = 0;
  args_info->remotelist_arg = NULL;
  args_info->remotelist_orig = NULL;
  args_info->attrlist_arg = NULL;
  args_info->attrlist_orig = NULL;
  
}

static
void init_args_info(struct icee_args_info *args_info)
{


  args_info->help_help = icee_args_info_help[0] ;
  args_info->version_help = icee_args_info_help[1] ;
  args_info->client_help = icee_args_info_help[2] ;
  args_info->writemethod_help = icee_args_info_help[3] ;
  args_info->readmethod_help = icee_args_info_help[4] ;
  args_info->len_help = icee_args_info_help[5] ;
  args_info->chunk_help = icee_args_info_help[6] ;
  args_info->timeout_help = icee_args_info_help[7] ;
  args_info->sleep_help = icee_args_info_help[8] ;
  args_info->nstep_help = icee_args_info_help[9] ;
  args_info->wparam_help = icee_args_info_help[10] ;
  args_info->rparam_help = icee_args_info_help[11] ;
  args_info->prefix_help = icee_args_info_help[12] ;
  args_info->append_help = icee_args_info_help[13] ;
  args_info->filename_help = icee_args_info_help[14] ;
  args_info->mpicolor_help = icee_args_info_help[15] ;
  args_info->filelock_help = icee_args_info_help[16] ;
  args_info->filelock_min = 2;
  args_info->filelock_max = 2;
  args_info->evilread_help = icee_args_info_help[17] ;
  args_info->commself_help = icee_args_info_help[18] ;
  args_info->host_help = icee_args_info_help[19] ;
  args_info->port_help = icee_args_info_help[20] ;
  args_info->remotehost_help = icee_args_info_help[21] ;
  args_info->remoteport_help = icee_args_info_help[22] ;
  args_info->method_help = icee_args_info_help[23] ;
  args_info->verbose_help = icee_args_info_help[24] ;
  args_info->contact_help = icee_args_info_help[25] ;
  args_info->passive_help = icee_args_info_help[26] ;
  args_info->nclient_help = icee_args_info_help[27] ;
  args_info->isnative_help = icee_args_info_help[28] ;
  args_info->remotelist_help = icee_args_info_help[29] ;
  args_info->attrlist_help = icee_args_info_help[30] ;
  
}

void
icee_cmdline_parser_print_version (void)
{
  printf ("%s %s\n",
     (strlen(ICEE_CMDLINE_PARSER_PACKAGE_NAME) ? ICEE_CMDLINE_PARSER_PACKAGE_NAME : ICEE_CMDLINE_PARSER_PACKAGE),
     ICEE_CMDLINE_PARSER_VERSION);

  if (strlen(icee_args_info_versiontext) > 0)
    printf("\n%s\n", icee_args_info_versiontext);
}

static void print_help_common(void) {
  icee_cmdline_parser_print_version ();

  if (strlen(icee_args_info_purpose) > 0)
    printf("\n%s\n", icee_args_info_purpose);

  if (strlen(icee_args_info_usage) > 0)
    printf("\n%s\n", icee_args_info_usage);

  printf("\n");

  if (strlen(icee_args_info_description) > 0)
    printf("%s\n\n", icee_args_info_description);
}

void
icee_cmdline_parser_print_help (void)
{
  int i = 0;
  print_help_common();
  while (icee_args_info_help[i])
    printf("%s\n", icee_args_info_help[i++]);
}

void
icee_cmdline_parser_init (struct icee_args_info *args_info)
{
  clear_given (args_info);
  clear_args (args_info);
  init_args_info (args_info);
}

void
icee_cmdline_parser_params_init(struct icee_cmdline_parser_params *params)
{
  if (params)
    { 
      params->override = 0;
      params->initialize = 1;
      params->check_required = 1;
      params->check_ambiguity = 0;
      params->print_errors = 1;
    }
}

struct icee_cmdline_parser_params *
icee_cmdline_parser_params_create(void)
{
  struct icee_cmdline_parser_params *params = 
    (struct icee_cmdline_parser_params *)malloc(sizeof(struct icee_cmdline_parser_params));
  icee_cmdline_parser_params_init(params);  
  return params;
}

static void
free_string_field (char **s)
{
  if (*s)
    {
      free (*s);
      *s = 0;
    }
}

/** @brief generic value variable */
union generic_value {
    int int_arg;
    float float_arg;
#if defined(HAVE_LONG_LONG) || defined(HAVE_LONG_LONG_INT)
    long long int longlong_arg;
#else
    long longlong_arg;
#endif
    char *string_arg;
    const char *default_string_arg;
};

/** @brief holds temporary values for multiple options */
struct generic_list
{
  union generic_value arg;
  char *orig;
  struct generic_list *next;
};

/**
 * @brief add a node at the head of the list 
 */
static void add_node(struct generic_list **list) {
  struct generic_list *new_node = (struct generic_list *) malloc (sizeof (struct generic_list));
  new_node->next = *list;
  *list = new_node;
  new_node->arg.string_arg = 0;
  new_node->orig = 0;
}


static void
free_multiple_string_field(unsigned int len, char ***arg, char ***orig)
{
  unsigned int i;
  if (*arg) {
    for (i = 0; i < len; ++i)
      {
        free_string_field(&((*arg)[i]));
        free_string_field(&((*orig)[i]));
      }
    free_string_field(&((*arg)[0])); /* free default string */

    free (*arg);
    *arg = 0;
    free (*orig);
    *orig = 0;
  }
}

static void
icee_cmdline_parser_release (struct icee_args_info *args_info)
{

  free_string_field (&(args_info->writemethod_arg));
  free_string_field (&(args_info->writemethod_orig));
  free_string_field (&(args_info->readmethod_arg));
  free_string_field (&(args_info->readmethod_orig));
  free_string_field (&(args_info->len_orig));
  free_string_field (&(args_info->chunk_orig));
  free_string_field (&(args_info->timeout_orig));
  free_string_field (&(args_info->sleep_orig));
  free_string_field (&(args_info->nstep_orig));
  free_string_field (&(args_info->wparam_arg));
  free_string_field (&(args_info->wparam_orig));
  free_string_field (&(args_info->rparam_arg));
  free_string_field (&(args_info->rparam_orig));
  free_string_field (&(args_info->prefix_arg));
  free_string_field (&(args_info->prefix_orig));
  free_string_field (&(args_info->filename_arg));
  free_string_field (&(args_info->filename_orig));
  free_string_field (&(args_info->mpicolor_orig));
  free_multiple_string_field (args_info->filelock_given, &(args_info->filelock_arg), &(args_info->filelock_orig));
  free_string_field (&(args_info->host_arg));
  free_string_field (&(args_info->host_orig));
  free_string_field (&(args_info->port_orig));
  free_string_field (&(args_info->remotehost_arg));
  free_string_field (&(args_info->remotehost_orig));
  free_string_field (&(args_info->remoteport_orig));
  free_string_field (&(args_info->method_arg));
  free_string_field (&(args_info->method_orig));
  free_string_field (&(args_info->verbose_orig));
  free_string_field (&(args_info->contact_arg));
  free_string_field (&(args_info->contact_orig));
  free_string_field (&(args_info->nclient_orig));
  free_string_field (&(args_info->remotelist_arg));
  free_string_field (&(args_info->remotelist_orig));
  free_string_field (&(args_info->attrlist_arg));
  free_string_field (&(args_info->attrlist_orig));
  
  

  clear_given (args_info);
}


static void
write_into_file(FILE *outfile, const char *opt, const char *arg, const char *values[])
{
  FIX_UNUSED (values);
  if (arg) {
    fprintf(outfile, "%s=\"%s\"\n", opt, arg);
  } else {
    fprintf(outfile, "%s\n", opt);
  }
}

static void
write_multiple_into_file(FILE *outfile, int len, const char *opt, char **arg, const char *values[])
{
  int i;
  
  for (i = 0; i < len; ++i)
    write_into_file(outfile, opt, (arg ? arg[i] : 0), values);
}

int
icee_cmdline_parser_dump(FILE *outfile, struct icee_args_info *args_info)
{
  int i = 0;

  if (!outfile)
    {
      fprintf (stderr, "%s: cannot dump options to stream\n", ICEE_CMDLINE_PARSER_PACKAGE);
      return EXIT_FAILURE;
    }

  if (args_info->help_given)
    write_into_file(outfile, "help", 0, 0 );
  if (args_info->version_given)
    write_into_file(outfile, "version", 0, 0 );
  if (args_info->client_given)
    write_into_file(outfile, "client", 0, 0 );
  if (args_info->writemethod_given)
    write_into_file(outfile, "writemethod", args_info->writemethod_orig, 0);
  if (args_info->readmethod_given)
    write_into_file(outfile, "readmethod", args_info->readmethod_orig, 0);
  if (args_info->len_given)
    write_into_file(outfile, "len", args_info->len_orig, 0);
  if (args_info->chunk_given)
    write_into_file(outfile, "chunk", args_info->chunk_orig, 0);
  if (args_info->timeout_given)
    write_into_file(outfile, "timeout", args_info->timeout_orig, 0);
  if (args_info->sleep_given)
    write_into_file(outfile, "sleep", args_info->sleep_orig, 0);
  if (args_info->nstep_given)
    write_into_file(outfile, "nstep", args_info->nstep_orig, 0);
  if (args_info->wparam_given)
    write_into_file(outfile, "wparam", args_info->wparam_orig, 0);
  if (args_info->rparam_given)
    write_into_file(outfile, "rparam", args_info->rparam_orig, 0);
  if (args_info->prefix_given)
    write_into_file(outfile, "prefix", args_info->prefix_orig, 0);
  if (args_info->append_given)
    write_into_file(outfile, "append", 0, 0 );
  if (args_info->filename_given)
    write_into_file(outfile, "filename", args_info->filename_orig, 0);
  if (args_info->mpicolor_given)
    write_into_file(outfile, "mpicolor", args_info->mpicolor_orig, 0);
  write_multiple_into_file(outfile, args_info->filelock_given, "filelock", args_info->filelock_orig, 0);
  if (args_info->evilread_given)
    write_into_file(outfile, "evilread", 0, 0 );
  if (args_info->commself_given)
    write_into_file(outfile, "commself", 0, 0 );
  if (args_info->host_given)
    write_into_file(outfile, "host", args_info->host_orig, 0);
  if (args_info->port_given)
    write_into_file(outfile, "port", args_info->port_orig, 0);
  if (args_info->remotehost_given)
    write_into_file(outfile, "remotehost", args_info->remotehost_orig, 0);
  if (args_info->remoteport_given)
    write_into_file(outfile, "remoteport", args_info->remoteport_orig, 0);
  if (args_info->method_given)
    write_into_file(outfile, "method", args_info->method_orig, 0);
  if (args_info->verbose_given)
    write_into_file(outfile, "verbose", args_info->verbose_orig, 0);
  if (args_info->contact_given)
    write_into_file(outfile, "contact", args_info->contact_orig, 0);
  if (args_info->passive_given)
    write_into_file(outfile, "passive", 0, 0 );
  if (args_info->nclient_given)
    write_into_file(outfile, "nclient", args_info->nclient_orig, 0);
  if (args_info->isnative_given)
    write_into_file(outfile, "isnative", 0, 0 );
  if (args_info->remotelist_given)
    write_into_file(outfile, "remotelist", args_info->remotelist_orig, 0);
  if (args_info->attrlist_given)
    write_into_file(outfile, "attrlist", args_info->attrlist_orig, 0);
  

  i = EXIT_SUCCESS;
  return i;
}

int
icee_cmdline_parser_file_save(const char *filename, struct icee_args_info *args_info)
{
  FILE *outfile;
  int i = 0;

  outfile = fopen(filename, "w");

  if (!outfile)
    {
      fprintf (stderr, "%s: cannot open file for writing: %s\n", ICEE_CMDLINE_PARSER_PACKAGE, filename);
      return EXIT_FAILURE;
    }

  i = icee_cmdline_parser_dump(outfile, args_info);
  fclose (outfile);

  return i;
}

void
icee_cmdline_parser_free (struct icee_args_info *args_info)
{
  icee_cmdline_parser_release (args_info);
}

/** @brief replacement of strdup, which is not standard */
char *
gengetopt_strdup (const char *s)
{
  char *result = 0;
  if (!s)
    return result;

  result = (char*)malloc(strlen(s) + 1);
  if (result == (char*)0)
    return (char*)0;
  strcpy(result, s);
  return result;
}

static char *
get_multiple_arg_token(const char *arg)
{
  const char *tok;
  char *ret;
  size_t len, num_of_escape, i, j;

  if (!arg)
    return 0;

  tok = strchr (arg, ',');
  num_of_escape = 0;

  /* make sure it is not escaped */
  while (tok)
    {
      if (*(tok-1) == '\\')
        {
          /* find the next one */
          tok = strchr (tok+1, ',');
          ++num_of_escape;
        }
      else
        break;
    }

  if (tok)
    len = (size_t)(tok - arg + 1);
  else
    len = strlen (arg) + 1;

  len -= num_of_escape;

  ret = (char *) malloc (len);

  i = 0;
  j = 0;
  while (arg[i] && (j < len-1))
    {
      if (arg[i] == '\\' && 
	  arg[ i + 1 ] && 
	  arg[ i + 1 ] == ',')
        ++i;

      ret[j++] = arg[i++];
    }

  ret[len-1] = '\0';

  return ret;
}

static const char *
get_multiple_arg_token_next(const char *arg)
{
  const char *tok;

  if (!arg)
    return 0;

  tok = strchr (arg, ',');

  /* make sure it is not escaped */
  while (tok)
    {
      if (*(tok-1) == '\\')
        {
          /* find the next one */
          tok = strchr (tok+1, ',');
        }
      else
        break;
    }

  if (! tok || strlen(tok) == 1)
    return 0;

  return tok+1;
}

static int
check_multiple_option_occurrences(const char *prog_name, unsigned int option_given, unsigned int min, unsigned int max, const char *option_desc);

int
check_multiple_option_occurrences(const char *prog_name, unsigned int option_given, unsigned int min, unsigned int max, const char *option_desc)
{
  int error_occurred = 0;

  if (option_given && (min > 0 || max > 0))
    {
      if (min > 0 && max > 0)
        {
          if (min == max)
            {
              /* specific occurrences */
              if (option_given != (unsigned int) min)
                {
                  fprintf (stderr, "%s: %s option occurrences must be %d\n",
                    prog_name, option_desc, min);
                  error_occurred = 1;
                }
            }
          else if (option_given < (unsigned int) min
                || option_given > (unsigned int) max)
            {
              /* range occurrences */
              fprintf (stderr, "%s: %s option occurrences must be between %d and %d\n",
                prog_name, option_desc, min, max);
              error_occurred = 1;
            }
        }
      else if (min > 0)
        {
          /* at least check */
          if (option_given < min)
            {
              fprintf (stderr, "%s: %s option occurrences must be at least %d\n",
                prog_name, option_desc, min);
              error_occurred = 1;
            }
        }
      else if (max > 0)
        {
          /* at most check */
          if (option_given > max)
            {
              fprintf (stderr, "%s: %s option occurrences must be at most %d\n",
                prog_name, option_desc, max);
              error_occurred = 1;
            }
        }
    }
    
  return error_occurred;
}
int
icee_cmdline_parser (int argc, char **argv, struct icee_args_info *args_info)
{
  return icee_cmdline_parser2 (argc, argv, args_info, 0, 1, 1);
}

int
icee_cmdline_parser_ext (int argc, char **argv, struct icee_args_info *args_info,
                   struct icee_cmdline_parser_params *params)
{
  int result;
  result = icee_cmdline_parser_internal (argc, argv, args_info, params, 0);

  if (result == EXIT_FAILURE)
    {
      icee_cmdline_parser_free (args_info);
      exit (EXIT_FAILURE);
    }
  
  return result;
}

int
icee_cmdline_parser2 (int argc, char **argv, struct icee_args_info *args_info, int override, int initialize, int check_required)
{
  int result;
  struct icee_cmdline_parser_params params;
  
  params.override = override;
  params.initialize = initialize;
  params.check_required = check_required;
  params.check_ambiguity = 0;
  params.print_errors = 1;

  result = icee_cmdline_parser_internal (argc, argv, args_info, &params, 0);

  if (result == EXIT_FAILURE)
    {
      icee_cmdline_parser_free (args_info);
      exit (EXIT_FAILURE);
    }
  
  return result;
}

int
icee_cmdline_parser_required (struct icee_args_info *args_info, const char *prog_name)
{
  int result = EXIT_SUCCESS;

  if (icee_cmdline_parser_required2(args_info, prog_name, 0) > 0)
    result = EXIT_FAILURE;

  if (result == EXIT_FAILURE)
    {
      icee_cmdline_parser_free (args_info);
      exit (EXIT_FAILURE);
    }
  
  return result;
}

int
icee_cmdline_parser_required2 (struct icee_args_info *args_info, const char *prog_name, const char *additional_error)
{
  int error_occurred = 0;
  FIX_UNUSED (additional_error);

  /* checks for required options */
  if (check_multiple_option_occurrences(prog_name, args_info->filelock_given, args_info->filelock_min, args_info->filelock_max, "'--filelock'"))
     error_occurred = 1;
  
  
  /* checks for dependences among options */

  return error_occurred;
}


static char *package_name = 0;

/**
 * @brief updates an option
 * @param field the generic pointer to the field to update
 * @param orig_field the pointer to the orig field
 * @param field_given the pointer to the number of occurrence of this option
 * @param prev_given the pointer to the number of occurrence already seen
 * @param value the argument for this option (if null no arg was specified)
 * @param possible_values the possible values for this option (if specified)
 * @param default_value the default value (in case the option only accepts fixed values)
 * @param arg_type the type of this option
 * @param check_ambiguity @see icee_cmdline_parser_params.check_ambiguity
 * @param override @see icee_cmdline_parser_params.override
 * @param no_free whether to free a possible previous value
 * @param multiple_option whether this is a multiple option
 * @param long_opt the corresponding long option
 * @param short_opt the corresponding short option (or '-' if none)
 * @param additional_error possible further error specification
 */
static
int update_arg(void *field, char **orig_field,
               unsigned int *field_given, unsigned int *prev_given, 
               char *value, const char *possible_values[],
               const char *default_value,
               icee_cmdline_parser_arg_type arg_type,
               int check_ambiguity, int override,
               int no_free, int multiple_option,
               const char *long_opt, char short_opt,
               const char *additional_error)
{
  char *stop_char = 0;
  const char *val = value;
  int found;
  char **string_field;
  FIX_UNUSED (field);

  stop_char = 0;
  found = 0;

  if (!multiple_option && prev_given && (*prev_given || (check_ambiguity && *field_given)))
    {
      if (short_opt != '-')
        fprintf (stderr, "%s: `--%s' (`-%c') option given more than once%s\n", 
               package_name, long_opt, short_opt,
               (additional_error ? additional_error : ""));
      else
        fprintf (stderr, "%s: `--%s' option given more than once%s\n", 
               package_name, long_opt,
               (additional_error ? additional_error : ""));
      return 1; /* failure */
    }

  FIX_UNUSED (default_value);
    
  if (field_given && *field_given && ! override)
    return 0;
  if (prev_given)
    (*prev_given)++;
  if (field_given)
    (*field_given)++;
  if (possible_values)
    val = possible_values[found];

  switch(arg_type) {
  case ARG_FLAG:
    *((int *)field) = !*((int *)field);
    break;
  case ARG_INT:
    if (val) *((int *)field) = strtol (val, &stop_char, 0);
    break;
  case ARG_FLOAT:
    if (val) *((float *)field) = (float)strtod (val, &stop_char);
    break;
  case ARG_LONGLONG:
#if defined(HAVE_LONG_LONG) || defined(HAVE_LONG_LONG_INT)
    if (val) *((long long int*)field) = (long long int) strtoll (val, &stop_char, 0);
#else
    if (val) *((long *)field) = (long)strtol (val, &stop_char, 0);
#endif
    break;
  case ARG_STRING:
    if (val) {
      string_field = (char **)field;
      if (!no_free && *string_field)
        free (*string_field); /* free previous string */
      *string_field = gengetopt_strdup (val);
    }
    break;
  default:
    break;
  };

  /* check numeric conversion */
  switch(arg_type) {
  case ARG_INT:
  case ARG_FLOAT:
  case ARG_LONGLONG:
    if (val && !(stop_char && *stop_char == '\0')) {
      fprintf(stderr, "%s: invalid numeric value: %s\n", package_name, val);
      return 1; /* failure */
    }
    break;
  default:
    ;
  };

  /* store the original value */
  switch(arg_type) {
  case ARG_NO:
  case ARG_FLAG:
    break;
  default:
    if (value && orig_field) {
      if (no_free) {
        *orig_field = value;
      } else {
        if (*orig_field)
          free (*orig_field); /* free previous string */
        *orig_field = gengetopt_strdup (value);
      }
    }
  };

  return 0; /* OK */
}

/**
 * @brief store information about a multiple option in a temporary list
 * @param list where to (temporarily) store multiple options
 */
static
int update_multiple_arg_temp(struct generic_list **list,
               unsigned int *prev_given, const char *val,
               const char *possible_values[], const char *default_value,
               icee_cmdline_parser_arg_type arg_type,
               const char *long_opt, char short_opt,
               const char *additional_error)
{
  /* store single arguments */
  char *multi_token;
  const char *multi_next;

  if (arg_type == ARG_NO) {
    (*prev_given)++;
    return 0; /* OK */
  }

  multi_token = get_multiple_arg_token(val);
  multi_next = get_multiple_arg_token_next (val);

  while (1)
    {
      add_node (list);
      if (update_arg((void *)&((*list)->arg), &((*list)->orig), 0,
          prev_given, multi_token, possible_values, default_value, 
          arg_type, 0, 1, 1, 1, long_opt, short_opt, additional_error)) {
        if (multi_token) free(multi_token);
        return 1; /* failure */
      }

      if (multi_next)
        {
          multi_token = get_multiple_arg_token(multi_next);
          multi_next = get_multiple_arg_token_next (multi_next);
        }
      else
        break;
    }

  return 0; /* OK */
}

/**
 * @brief free the passed list (including possible string argument)
 */
static
void free_list(struct generic_list *list, short string_arg)
{
  if (list) {
    struct generic_list *tmp;
    while (list)
      {
        tmp = list;
        if (string_arg && list->arg.string_arg)
          free (list->arg.string_arg);
        if (list->orig)
          free (list->orig);
        list = list->next;
        free (tmp);
      }
  }
}

/**
 * @brief updates a multiple option starting from the passed list
 */
static
void update_multiple_arg(void *field, char ***orig_field,
               unsigned int field_given, unsigned int prev_given, union generic_value *default_value,
               icee_cmdline_parser_arg_type arg_type,
               struct generic_list *list)
{
  int i;
  struct generic_list *tmp;

  if (prev_given && list) {
    *orig_field = (char **) realloc (*orig_field, (field_given + prev_given) * sizeof (char *));

    switch(arg_type) {
    case ARG_INT:
      *((int **)field) = (int *)realloc (*((int **)field), (field_given + prev_given) * sizeof (int)); break;
    case ARG_FLOAT:
      *((float **)field) = (float *)realloc (*((float **)field), (field_given + prev_given) * sizeof (float)); break;
    case ARG_LONGLONG:
#if defined(HAVE_LONG_LONG) || defined(HAVE_LONG_LONG_INT)
      *((long long int **)field) = (long long int *)realloc (*((long long int **)field), (field_given + prev_given) * sizeof (long long int)); break;
#else
      *((long **)field) = (long *)realloc (*((long **)field), (field_given + prev_given) * sizeof (long)); break;
#endif
    case ARG_STRING:
      *((char ***)field) = (char **)realloc (*((char ***)field), (field_given + prev_given) * sizeof (char *)); break;
    default:
      break;
    };
    
    for (i = (prev_given - 1); i >= 0; --i)
      {
        tmp = list;
        
        switch(arg_type) {
        case ARG_INT:
          (*((int **)field))[i + field_given] = tmp->arg.int_arg; break;
        case ARG_FLOAT:
          (*((float **)field))[i + field_given] = tmp->arg.float_arg; break;
        case ARG_LONGLONG:
#if defined(HAVE_LONG_LONG) || defined(HAVE_LONG_LONG_INT)
          (*((long long int **)field))[i + field_given] = tmp->arg.longlong_arg; break;
#else
          (*((long **)field))[i + field_given] = tmp->arg.longlong_arg; break;
#endif
        case ARG_STRING:
          (*((char ***)field))[i + field_given] = tmp->arg.string_arg; break;
        default:
          break;
        }        
        (*orig_field) [i + field_given] = list->orig;
        list = list->next;
        free (tmp);
      }
  } else { /* set the default value */
    if (default_value && ! field_given) {
      switch(arg_type) {
      case ARG_INT:
        if (! *((int **)field)) {
          *((int **)field) = (int *)malloc (sizeof (int));
          (*((int **)field))[0] = default_value->int_arg; 
        }
        break;
      case ARG_FLOAT:
        if (! *((float **)field)) {
          *((float **)field) = (float *)malloc (sizeof (float));
          (*((float **)field))[0] = default_value->float_arg;
        }
        break;
      case ARG_LONGLONG:
#if defined(HAVE_LONG_LONG) || defined(HAVE_LONG_LONG_INT)
        if (! *((long long int **)field)) {
          *((long long int **)field) = (long long int *)malloc (sizeof (long long int));
          (*((long long int **)field))[0] = default_value->longlong_arg;
        }
#else
        if (! *((long **)field)) {
          *((long **)field) = (long *)malloc (sizeof (long));
          (*((long **)field))[0] = default_value->longlong_arg;
        }
#endif
        break;
      case ARG_STRING:
        if (! *((char ***)field)) {
          *((char ***)field) = (char **)malloc (sizeof (char *));
          (*((char ***)field))[0] = gengetopt_strdup(default_value->string_arg);
        }
        break;
      default: break;
      }
      if (!(*orig_field)) {
        *orig_field = (char **) malloc (sizeof (char *));
        (*orig_field)[0] = 0;
      }
    }
  }
}

int
icee_cmdline_parser_internal (
  int argc, char **argv, struct icee_args_info *args_info,
                        struct icee_cmdline_parser_params *params, const char *additional_error)
{
  int c;	/* Character of the parsed option.  */

  struct generic_list * filelock_list = NULL;
  int error_occurred = 0;
  struct icee_args_info local_args_info;
  
  int override;
  int initialize;
  int check_required;
  int check_ambiguity;
  
  package_name = argv[0];
  
  override = params->override;
  initialize = params->initialize;
  check_required = params->check_required;
  check_ambiguity = params->check_ambiguity;

  if (initialize)
    icee_cmdline_parser_init (args_info);

  icee_cmdline_parser_init (&local_args_info);

  optarg = 0;
  optind = 0;
  opterr = params->print_errors;
  optopt = '?';

  while (1)
    {
      int option_index = 0;

      static struct option long_options[] = {
        { "help",	0, NULL, 'h' },
        { "version",	0, NULL, 'V' },
        { "client",	0, NULL, 'c' },
        { "writemethod",	1, NULL, 'w' },
        { "readmethod",	1, NULL, 'r' },
        { "len",	1, NULL, 'n' },
        { "chunk",	1, NULL, 0 },
        { "timeout",	1, NULL, 0 },
        { "sleep",	1, NULL, 0 },
        { "nstep",	1, NULL, 0 },
        { "wparam",	1, NULL, 0 },
        { "rparam",	1, NULL, 0 },
        { "prefix",	1, NULL, 0 },
        { "append",	0, NULL, 0 },
        { "filename",	1, NULL, 0 },
        { "mpicolor",	1, NULL, 0 },
        { "filelock",	1, NULL, 0 },
        { "evilread",	0, NULL, 0 },
        { "commself",	0, NULL, 0 },
        { "host",	1, NULL, 0 },
        { "port",	1, NULL, 'p' },
        { "remotehost",	1, NULL, 's' },
        { "remoteport",	1, NULL, 't' },
        { "method",	1, NULL, 'T' },
        { "verbose",	1, NULL, 'v' },
        { "contact",	1, NULL, 'e' },
        { "passive",	0, NULL, 0 },
        { "nclient",	1, NULL, 0 },
        { "isnative",	0, NULL, 0 },
        { "remotelist",	1, NULL, 0 },
        { "attrlist",	1, NULL, 'a' },
        { 0,  0, 0, 0 }
      };

      c = getopt_long (argc, argv, "hVcw:r:n:p:s:t:T:v:e:a:", long_options, &option_index);

      if (c == -1) break;	/* Exit from `while (1)' loop.  */

      switch (c)
        {
        case 'h':	/* Print help and exit.  */
          icee_cmdline_parser_print_help ();
          icee_cmdline_parser_free (&local_args_info);
          exit (EXIT_SUCCESS);

        case 'V':	/* Print version and exit.  */
        
        
          if (update_arg( 0 , 
               0 , &(args_info->version_given),
              &(local_args_info.version_given), optarg, 0, 0, ARG_NO,
              check_ambiguity, override, 0, 0,
              "version", 'V',
              additional_error))
            goto failure;
          icee_cmdline_parser_free (&local_args_info);
          return 0;
        
          break;
        case 'c':	/* Client mode.  */
        
        
          if (update_arg((void *)&(args_info->client_flag), 0, &(args_info->client_given),
              &(local_args_info.client_given), optarg, 0, 0, ARG_FLAG,
              check_ambiguity, override, 1, 0, "client", 'c',
              additional_error))
            goto failure;
        
          break;
        case 'w':	/* ADIOS write method.  */
        
        
          if (update_arg( (void *)&(args_info->writemethod_arg), 
               &(args_info->writemethod_orig), &(args_info->writemethod_given),
              &(local_args_info.writemethod_given), optarg, 0, "POSIX1", ARG_STRING,
              check_ambiguity, override, 0, 0,
              "writemethod", 'w',
              additional_error))
            goto failure;
        
          break;
        case 'r':	/* ADIOS read method.  */
        
        
          if (update_arg( (void *)&(args_info->readmethod_arg), 
               &(args_info->readmethod_orig), &(args_info->readmethod_given),
              &(local_args_info.readmethod_given), optarg, 0, "BP", ARG_STRING,
              check_ambiguity, override, 0, 0,
              "readmethod", 'r',
              additional_error))
            goto failure;
        
          break;
        case 'n':	/* array length.  */
        
        
          if (update_arg( (void *)&(args_info->len_arg), 
               &(args_info->len_orig), &(args_info->len_given),
              &(local_args_info.len_given), optarg, 0, "1", ARG_LONGLONG,
              check_ambiguity, override, 0, 0,
              "len", 'n',
              additional_error))
            goto failure;
        
          break;
        case 'p':	/* local port.  */
        
        
          if (update_arg( (void *)&(args_info->port_arg), 
               &(args_info->port_orig), &(args_info->port_given),
              &(local_args_info.port_given), optarg, 0, "59900", ARG_INT,
              check_ambiguity, override, 0, 0,
              "port", 'p',
              additional_error))
            goto failure;
        
          break;
        case 's':	/* remote hostname.  */
        
        
          if (update_arg( (void *)&(args_info->remotehost_arg), 
               &(args_info->remotehost_orig), &(args_info->remotehost_given),
              &(local_args_info.remotehost_given), optarg, 0, "localhost", ARG_STRING,
              check_ambiguity, override, 0, 0,
              "remotehost", 's',
              additional_error))
            goto failure;
        
          break;
        case 't':	/* remote port.  */
        
        
          if (update_arg( (void *)&(args_info->remoteport_arg), 
               &(args_info->remoteport_orig), &(args_info->remoteport_given),
              &(local_args_info.remoteport_given), optarg, 0, "59900", ARG_INT,
              check_ambiguity, override, 0, 0,
              "remoteport", 't',
              additional_error))
            goto failure;
        
          break;
        case 'T':	/* EVPath method.  */
        
        
          if (update_arg( (void *)&(args_info->method_arg), 
               &(args_info->method_orig), &(args_info->method_given),
              &(local_args_info.method_given), optarg, 0, "TCP", ARG_STRING,
              check_ambiguity, override, 0, 0,
              "method", 'T',
              additional_error))
            goto failure;
        
          break;
        case 'v':	/* verbosity level.  */
        
        
          if (update_arg( (void *)&(args_info->verbose_arg), 
               &(args_info->verbose_orig), &(args_info->verbose_given),
              &(local_args_info.verbose_given), optarg, 0, "3", ARG_INT,
              check_ambiguity, override, 0, 0,
              "verbose", 'v',
              additional_error))
            goto failure;
        
          break;
        case 'e':	/* EVPath contact string.  */
        
        
          if (update_arg( (void *)&(args_info->contact_arg), 
               &(args_info->contact_orig), &(args_info->contact_given),
              &(local_args_info.contact_given), optarg, 0, 0, ARG_STRING,
              check_ambiguity, override, 0, 0,
              "contact", 'e',
              additional_error))
            goto failure;
        
          break;
        case 'a':	/* attr list.  */
        
        
          if (update_arg( (void *)&(args_info->attrlist_arg), 
               &(args_info->attrlist_orig), &(args_info->attrlist_given),
              &(local_args_info.attrlist_given), optarg, 0, 0, ARG_STRING,
              check_ambiguity, override, 0, 0,
              "attrlist", 'a',
              additional_error))
            goto failure;
        
          break;

        case 0:	/* Long option with no short option */
          /* chunk length.  */
          if (strcmp (long_options[option_index].name, "chunk") == 0)
          {
          
          
            if (update_arg( (void *)&(args_info->chunk_arg), 
                 &(args_info->chunk_orig), &(args_info->chunk_given),
                &(local_args_info.chunk_given), optarg, 0, "131072", ARG_LONGLONG,
                check_ambiguity, override, 0, 0,
                "chunk", '-',
                additional_error))
              goto failure;
          
          }
          /* Timeout.  */
          else if (strcmp (long_options[option_index].name, "timeout") == 0)
          {
          
          
            if (update_arg( (void *)&(args_info->timeout_arg), 
                 &(args_info->timeout_orig), &(args_info->timeout_given),
                &(local_args_info.timeout_given), optarg, 0, "10.0", ARG_FLOAT,
                check_ambiguity, override, 0, 0,
                "timeout", '-',
                additional_error))
              goto failure;
          
          }
          /* interval time.  */
          else if (strcmp (long_options[option_index].name, "sleep") == 0)
          {
          
          
            if (update_arg( (void *)&(args_info->sleep_arg), 
                 &(args_info->sleep_orig), &(args_info->sleep_given),
                &(local_args_info.sleep_given), optarg, 0, "5", ARG_INT,
                check_ambiguity, override, 0, 0,
                "sleep", '-',
                additional_error))
              goto failure;
          
          }
          /* number of time steps.  */
          else if (strcmp (long_options[option_index].name, "nstep") == 0)
          {
          
          
            if (update_arg( (void *)&(args_info->nstep_arg), 
                 &(args_info->nstep_orig), &(args_info->nstep_given),
                &(local_args_info.nstep_given), optarg, 0, "10", ARG_INT,
                check_ambiguity, override, 0, 0,
                "nstep", '-',
                additional_error))
              goto failure;
          
          }
          /* write method params.  */
          else if (strcmp (long_options[option_index].name, "wparam") == 0)
          {
          
          
            if (update_arg( (void *)&(args_info->wparam_arg), 
                 &(args_info->wparam_orig), &(args_info->wparam_given),
                &(local_args_info.wparam_given), optarg, 0, "", ARG_STRING,
                check_ambiguity, override, 0, 0,
                "wparam", '-',
                additional_error))
              goto failure;
          
          }
          /* read method params.  */
          else if (strcmp (long_options[option_index].name, "rparam") == 0)
          {
          
          
            if (update_arg( (void *)&(args_info->rparam_arg), 
                 &(args_info->rparam_orig), &(args_info->rparam_given),
                &(local_args_info.rparam_given), optarg, 0, "", ARG_STRING,
                check_ambiguity, override, 0, 0,
                "rparam", '-',
                additional_error))
              goto failure;
          
          }
          /* prefix.  */
          else if (strcmp (long_options[option_index].name, "prefix") == 0)
          {
          
          
            if (update_arg( (void *)&(args_info->prefix_arg), 
                 &(args_info->prefix_orig), &(args_info->prefix_given),
                &(local_args_info.prefix_given), optarg, 0, "", ARG_STRING,
                check_ambiguity, override, 0, 0,
                "prefix", '-',
                additional_error))
              goto failure;
          
          }
          /* append.  */
          else if (strcmp (long_options[option_index].name, "append") == 0)
          {
          
          
            if (update_arg((void *)&(args_info->append_flag), 0, &(args_info->append_given),
                &(local_args_info.append_given), optarg, 0, 0, ARG_FLAG,
                check_ambiguity, override, 1, 0, "append", '-',
                additional_error))
              goto failure;
          
          }
          /* filename.  */
          else if (strcmp (long_options[option_index].name, "filename") == 0)
          {
          
          
            if (update_arg( (void *)&(args_info->filename_arg), 
                 &(args_info->filename_orig), &(args_info->filename_given),
                &(local_args_info.filename_given), optarg, 0, 0, ARG_STRING,
                check_ambiguity, override, 0, 0,
                "filename", '-',
                additional_error))
              goto failure;
          
          }
          /* MPI comm color.  */
          else if (strcmp (long_options[option_index].name, "mpicolor") == 0)
          {
          
          
            if (update_arg( (void *)&(args_info->mpicolor_arg), 
                 &(args_info->mpicolor_orig), &(args_info->mpicolor_given),
                &(local_args_info.mpicolor_given), optarg, 0, "0", ARG_INT,
                check_ambiguity, override, 0, 0,
                "mpicolor", '-',
                additional_error))
              goto failure;
          
          }
          /* filelock name.  */
          else if (strcmp (long_options[option_index].name, "filelock") == 0)
          {
          
            if (update_multiple_arg_temp(&filelock_list, 
                &(local_args_info.filelock_given), optarg, 0, 0, ARG_STRING,
                "filelock", '-',
                additional_error))
              goto failure;
          
          }
          /* enable evil read.  */
          else if (strcmp (long_options[option_index].name, "evilread") == 0)
          {
          
          
            if (update_arg((void *)&(args_info->evilread_flag), 0, &(args_info->evilread_given),
                &(local_args_info.evilread_given), optarg, 0, 0, ARG_FLAG,
                check_ambiguity, override, 1, 0, "evilread", '-',
                additional_error))
              goto failure;
          
          }
          /* commself.  */
          else if (strcmp (long_options[option_index].name, "commself") == 0)
          {
          
          
            if (update_arg((void *)&(args_info->commself_flag), 0, &(args_info->commself_given),
                &(local_args_info.commself_given), optarg, 0, 0, ARG_FLAG,
                check_ambiguity, override, 1, 0, "commself", '-',
                additional_error))
              goto failure;
          
          }
          /* local hostname.  */
          else if (strcmp (long_options[option_index].name, "host") == 0)
          {
          
          
            if (update_arg( (void *)&(args_info->host_arg), 
                 &(args_info->host_orig), &(args_info->host_given),
                &(local_args_info.host_given), optarg, 0, "localhost", ARG_STRING,
                check_ambiguity, override, 0, 0,
                "host", '-',
                additional_error))
              goto failure;
          
          }
          /* enable passive mode.  */
          else if (strcmp (long_options[option_index].name, "passive") == 0)
          {
          
          
            if (update_arg((void *)&(args_info->passive_flag), 0, &(args_info->passive_given),
                &(local_args_info.passive_given), optarg, 0, 0, ARG_FLAG,
                check_ambiguity, override, 1, 0, "passive", '-',
                additional_error))
              goto failure;
          
          }
          /* maximum number of clients.  */
          else if (strcmp (long_options[option_index].name, "nclient") == 0)
          {
          
          
            if (update_arg( (void *)&(args_info->nclient_arg), 
                 &(args_info->nclient_orig), &(args_info->nclient_given),
                &(local_args_info.nclient_given), optarg, 0, 0, ARG_INT,
                check_ambiguity, override, 0, 0,
                "nclient", '-',
                additional_error))
              goto failure;
          
          }
          /* use native contact.  */
          else if (strcmp (long_options[option_index].name, "isnative") == 0)
          {
          
          
            if (update_arg((void *)&(args_info->isnative_flag), 0, &(args_info->isnative_given),
                &(local_args_info.isnative_given), optarg, 0, 0, ARG_FLAG,
                check_ambiguity, override, 1, 0, "isnative", '-',
                additional_error))
              goto failure;
          
          }
          /* remote list.  */
          else if (strcmp (long_options[option_index].name, "remotelist") == 0)
          {
          
          
            if (update_arg( (void *)&(args_info->remotelist_arg), 
                 &(args_info->remotelist_orig), &(args_info->remotelist_given),
                &(local_args_info.remotelist_given), optarg, 0, 0, ARG_STRING,
                check_ambiguity, override, 0, 0,
                "remotelist", '-',
                additional_error))
              goto failure;
          
          }
          
          break;
        case '?':	/* Invalid option.  */
          /* `getopt_long' already printed an error message.  */
          goto failure;

        default:	/* bug: option not considered.  */
          fprintf (stderr, "%s: option unknown: %c%s\n", ICEE_CMDLINE_PARSER_PACKAGE, c, (additional_error ? additional_error : ""));
          abort ();
        } /* switch */
    } /* while */


  update_multiple_arg((void *)&(args_info->filelock_arg),
    &(args_info->filelock_orig), args_info->filelock_given,
    local_args_info.filelock_given, 0,
    ARG_STRING, filelock_list);

  args_info->filelock_given += local_args_info.filelock_given;
  local_args_info.filelock_given = 0;
  
  if (check_required)
    {
      error_occurred += icee_cmdline_parser_required2 (args_info, argv[0], additional_error);
    }

  icee_cmdline_parser_release (&local_args_info);

  if ( error_occurred )
    return (EXIT_FAILURE);

  return 0;

failure:
  free_list (filelock_list, 1 );
  
  icee_cmdline_parser_release (&local_args_info);
  return (EXIT_FAILURE);
}
